### ISSUE TITLE
.get_datatable не работает при слишком большой таблице

### ISSUE THREAD

**Issue by pixml27** [epoch8/datapipe#130]
При выполнении команды 
`catalog.get_datatable(ds,'name') `
Появляется ошибка "stack depth limit exceeded HINT: Increase the configuration parameter "max_stack_depth" "

**Comment by elephantum** [comment]
@pixml27 научи воспроизводить проблему

**Comment by elephantum** [comment]
решили ограничением сложности запроса и батчеванием
